version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pconnection

volumes:
    pgdata:

networks:
  pconnection:
