version: "3.1"

services:
  db:
    image: postgres
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ".env"
    volumes: 
      - ./:/usr/app
    ports:
        - 8000:8000
    depends_on: 
      - "redis"
      - "db"
    links:
      - "redis:redis"
    networks:
      - webnet
    
  redis:
    env_file:
      - ".env"
    image: "redis:6.0.7-alpine"
    ports:
      - '6379:6379'
    volumes:
      - "redis:/data"
    networks:
      - webnet
    restart: on-failure

  worker:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - "db"
      - "redis"
    env_file:
      - ".env"
    networks:
      - webnet
    links:
      - "redis:redis"
    restart: on-failure

networks:
  webnet:

volumes:
  redis: {}

