# Generated by Django 3.1.1 on 2020-09-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20200922_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_data', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'file',
                'ordering': ['title'],
            },
        ),
    ]
